dubbo:
  application:
    name: sms-service
  registry:
    protocol: zookeeper
    address: 106.13.208.154:2181
  protocol:
    port: '20882'
server:
  port: 8096
spring:
  rabbitmq:
    host: 106.13.208.154
    port: 5672
    username: yu
    password: 123
    virtual-host: java1907