dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 106.13.208.154:2181
  protocol:
    port: '20881'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v1?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  data:
    solr:
      host: http://106.13.208.154:8080/solr
server:
  port: 8093
