dubbo:
  application:
    name: web-center
  registry:
    protocol: zookeeper
    address: 106.13.208.154:2181
server:
  port: 9089
spring:
  thymeleaf:
    cache: false
  servlet:
      multipart:
        max-file-size: 10MB
  rabbitmq:
    host: 106.13.208.154
    port: 5672
    username: yu
    password: 123
    virtual-host: java1907
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 300
    height: 300
  tracker-list: 106.13.208.154:22122
image:
  server: http://106.13.208.154/


