dubbo:
  application:
    name: product-service
  registry:
    address: zookeeper://106.13.208.154:2181
  protocol:
    port: '20880'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 106.13.208.154
    port: 6379
    password: yu
  rabbitmq:
    host: 106.13.208.154
    port: 5672
    username: yu
    password: 123
    virtual-host: java1907
pagehelper:
  helper-dialect: mysql
  reasonable: true