dubbo:
  application:
    name: web-center
  registry:
    protocol: zookeeper
    address: 106.13.208.154:2181
server:
  port: 9092
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 106.13.208.154
    port: 5672
    username: yu
    password: 123
    virtual-host: java1907
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

