dubbo:
  application:
    name: user-service
  registry:
    protocol: zookeeper
    address: 106.13.208.154:2181
  protocol:
    port: '20883'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 106.13.208.154
    port: 6379
    password: yu
server:
  port: 8094